dataset:
  name: 'imdb'
  folder-path: 'data/imdb'
  data-file: 'train.txt.npy'
  vocab-file: 'vocab.pkl'
  labels: ['negative', 'positive']
  num_classes: 2

model:
  name: 'aviad'
  n_encoder_1: 100
  n_encoder_2: 100
  n_latent: 3 # match the number of aspects ('food', 'staff', 'ambience')
  dropout: 0.6
  lambda: 20.0
  alpha: 1.0

training:
  lr: 0.0005  # 0.002
  bs: 400
  d_step: 50
  epochs: 300 # 20
  n_topwords: 50
  ratio: 0.2
  exp: 1
  result: 'results/imdb'
  write: True
