dataset:
  name: 'ursa'
  folder-path: 'data/User Review Structure Analysis (URSA)/1k'
  data-file: 'train.txt.npy'
  vocab-file: 'vocab.pkl'
  sw-file: 'seed_words.txt' # seed words 'food', 'staff', 'ambience'

model:
  name: 'aviad'
  n_encoder_1: 100
  n_encoder_2: 100
  n_latent: 3 # match the number of aspects ('food', 'staff', 'ambience')
  dropout: 0.5

training:
  lr: 0.002  # 0.002
  bs: 200
  d_step: 5
  epochs: 300 # 20
