preprocess:
  name: 'ursa'
  folder-path: 'data/User Review Structure Analysis (URSA)/'
  xml: 'Classified_Corpus.xml'
  save-path: 'data/User Review Structure Analysis (URSA)/'
  seed-word: 'seed_words.txt'
  vocab: 'vocab.pkl'
  review-tag: './/Review'
  polarity-tags: ['Positive', 'Negative', 'Neutral']
  food-tag: 'Food'
  staff-tag: 'Staff'
  ambiance-tag: 'Ambience'

dataset:
  name: 'ursa'
  folder-path: 'data/User Review Structure Analysis (URSA)/1k'
  data: 'train.txt.npy'
  seed-word: 'seed_words.txt'
  vocab: 'vocab.pkl'

training:
  lr: 0.001  # 0.000006
  grad-clip: 2.0
  max-violation: True
  loss-type: 'alignment'
  alignment-mode: 'MwSr'
  measure: 'dot'
  margin: 0.2
  bs: 40
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 20
  warmup: null
  warmup-period: 1000
